### 列表
GET  http://localhost:3000/api/records

### 项目下的记录列表
GET  http://localhost:3000/api/record/2

### 新建
POST http://localhost:3000/api/record
Content-Type: application/json

{
    "title": "title",
    "description": "desc",
    "status": 1,
    "project_id": 3
}

### 修改
POST http://localhost:3000/api/record
Content-Type: application/json

{
    "id": 5,
    "title": "title update",
    "description": "desc update",
    "status": 2,
    "project_id": 2
}

### 删除
DELETE http://localhost:3000/api/record/2
